### ISSUE TITLE
Turkish language pack

### ISSUE THREAD

**Issue by ghost** [pe7er/mod_db8colors#3]
Thanks for the module. Turkish language package (zip) is attached.

[tr-TR.zip](https://github.com/pe7er/mod_db8colors/files/14625443/tr-TR.zip)

**Comment by pe7er** [comment]
You're welcome @joomlaphp. Thanks for the Turkish language pack!

**Comment by pe7er** [comment]
I've added your translation & released version 1.0.5: https://github.com/pe7er/mod_db8colors/releases/tag/1.0.5
Thanks!
